global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'proposal-monitor'

scrape_configs:

  - job_name: 'proposal'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]